create table categories (
  id int primary key generated by default as identity,
  name varchar not null,
  parent_id int references categories (id) on update cascade on delete set null,
  type varchar,
  ordinance int,
  status varchar not null default 'available',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index unique_name_parent_id on categories (name, parent_id) where parent_id is not null;

create trigger handle_updated_at before update on categories
  for each row execute procedure moddatetime (updated_at);

alter publication supabase_realtime add table categories;